version: '3'

services:
  game-server:
    build:
      context: game-server
      args:
        - JAVA_VERSION=${JAVA_VERSION?:Please set the java version to a valid docker image name in the .env file. See the readme for more troubleshooting information.}
        - SERVER_DOWNLOAD_URL=${SERVER_DOWNLOAD_URL:?Please set the server download URL in the .env file. See the readme for more troubleshooting information.}
    restart: unless-stopped
    volumes:
      - ./save-data:/root/.config/Necesse
    # Unable to figure out how to change the game server to listen on 0.0.0.0,
    # so using this until I can figure that out (probably easiest to add a proxy?)
    network_mode: host
    # ports:
    #   - "14159:14159"
    command: -world ${WORLD_NAME:?Please set the world name in the .env file. See the readme for more troubleshooting information.}
